version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media
    restart: always

volumes:
  static-volume:
  media-volume:

