version: '3'

volumes:
  static-volume:
  media-volume:

services:
  api:
    build: lmsapi
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media
