version: '3.7'


services:
  api:
    build: lmsapi
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media

volumes:
  static-volume:
    driver: local
  media-volume:
    driver: local
