version: '3'

services:
  api:
    build:
      context: ./lmsapi
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media
    restart: always
    image: lmsapi

  nginx-proxy:
    build: ./nginx
    restart: always
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static-volume:
    driver: local
  media-volume:
    driver: local
  certs:
  html:
  vhost:
  acme:

