# Generated by Django 3.0.7 on 2020-09-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'macs',
                'managed': False,
            },
        ),
    ]
