# Generated by Django 3.1.2 on 2020-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_nodes', '0002_macs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtIphistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CID', null=True)),
                ('typ', models.CharField(blank=True, db_column='TYP', max_length=1, null=True)),
                ('uzivatel', models.TextField(blank=True, db_column='UZIVATEL', null=True)),
                ('datum', models.DateTimeField(blank=True, db_column='DATUM', null=True)),
            ],
            options={
                'db_table': 'bt_iphistory',
                'managed': False,
            },
        ),
    ]
