# Generated by Django 2.2.13 on 2020-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutersOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('identity', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True, null=True)),
                ('lastbackup', models.DateTimeField(blank=True, null=True)),
                ('sleeptime', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'routers',
            },
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('identity', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True, null=True)),
                ('lastbackup', models.DateTimeField(blank=True, null=True)),
                ('sleeptime', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'routers',
            },
        ),
    ]
