# Generated by Django 3.1.2 on 2020-10-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='devtype',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dev_type', to='api_rbbackup.routerstype'),
        ),
    ]
