# Generated by Django 3.1.2 on 2020-10-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0002_auto_20201001_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='sleeptime',
            field=models.SmallIntegerField(default=0),
        ),
    ]
