# Generated by Django 3.1.3 on 2020-11-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0002_auto_20201030_1552'),
        ('api_rbbackup', '0003_auto_20201002_2217'),
    ]

    operations = [
    ]
