# Generated by Django 3.0.9 on 2020-08-04 00:16

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    RoutersType = apps.get_model("api_rbbackup", "RoutersType")
    RoutersType.objects.bulk_create([
        RoutersType(type="Mikrotik"),
        RoutersType(type="Ubnt")
    ])


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0004_routerstype'),
    ]

    operations = [
        migrations.RunPython(forwards_func, rev)
    ]
