# Generated by Django 3.1.7 on 2021-03-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0004_merge_20201105_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='devtype',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='router_type', to='api_rbbackup.routerstype'),
        ),
    ]
