# Generated by Django 3.2.13 on 2022-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0007_alter_routerstype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='backup_result',
            field=models.CharField(choices=[('N', 'Neprobehlo'), ('OK', 'Uspesne'), ('ERLOG', 'Neuspesne prihlaseni'), ('ERDOWN', 'Chyba pri prenosu zalohy')], default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='routers',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
