# Generated by Django 3.0.7 on 2020-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netdevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hwtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hw_profile', models.CharField(max_length=50)),
                ('ports', models.IntegerField()),
                ('shortname', models.CharField(max_length=10)),
                ('def_wlan_freq', models.IntegerField(blank=True, null=True)),
                ('def_wlan_ch_width', models.IntegerField(blank=True, null=True)),
                ('def_wlan_antenna', models.IntegerField(blank=True, null=True)),
                ('def_wlan_polarization', models.IntegerField(blank=True, null=True)),
                ('oidmacvlanadr', models.CharField(max_length=100)),
                ('oidmacvlandescr', models.CharField(max_length=100)),
                ('oidmacvlanvlanid', models.CharField(max_length=100)),
                ('oidmacvlanstatus', models.CharField(max_length=100)),
                ('oidvlanid', models.CharField(max_length=100)),
                ('oidvlandescr', models.CharField(max_length=100)),
                ('oidvlanstatus', models.CharField(max_length=100)),
                ('snmp_portconfig', models.TextField()),
            ],
            options={
                'db_table': 'hwtypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Netcontypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=15)),
                ('popis', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'netcontypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nmsgroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'nmsgroups',
                'managed': False,
            },
        ),
    ]
