# Generated by Django 3.0.8 on 2020-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('ipaddr', models.PositiveIntegerField(unique=True)),
                ('ipaddr_pub', models.PositiveIntegerField()),
                ('passwd', models.CharField(max_length=32)),
                ('ownerid', models.IntegerField()),
                ('creationdate', models.IntegerField()),
                ('moddate', models.IntegerField()),
                ('creatorid', models.IntegerField()),
                ('modid', models.IntegerField()),
                ('netdev', models.IntegerField()),
                ('linktype', models.IntegerField()),
                ('port', models.SmallIntegerField()),
                ('access', models.IntegerField()),
                ('warning', models.IntegerField()),
                ('chkmac', models.IntegerField()),
                ('halfduplex', models.IntegerField()),
                ('lastonline', models.IntegerField()),
                ('info', models.TextField()),
                ('location', models.TextField()),
                ('nas', models.IntegerField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('linkspeed', models.IntegerField()),
                ('kod_adm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
    ]
