# Generated by Django 2.2.13 on 2020-08-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutersOld',
        ),
    ]
