# Generated by Django 2.2.13 on 2020-08-03 14:55

from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model('api_rbbackup', 'RoutersOld')
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model('api_rbbackup', 'Routers')
    NewModel.objects.bulk_create(
        NewModel(
            id=old_object.id,
            addr=old_object.addr,
            port=old_object.port,
            identity=old_object.identity,
            created=old_object.created,
            modify=old_object.modify,
            lastbackup=old_object.lastbackup,
            sleeptime=old_object.sleeptime

        )
        for old_object in OldModel.objects.using('rbackup').all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
