# Generated by Django 3.0.9 on 2020-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0002_delete_routersold'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='isActivated',
            field=models.BooleanField(default=False),
        ),
    ]
