# Generated by Django 3.0.9 on 2020-08-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rbbackup', '0005_auto_20200804_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='devtype',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api_rbbackup.RoutersType'),
        ),
    ]
