# Generated by Django 3.0.8 on 2020-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerassignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'customerassignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customercontacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customercontacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customergroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'customergroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField(choices=[(1, 'Zájemce'), (2, 'Čekající'), (3, 'Připojený')])),
                ('type', models.SmallIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=32)),
                ('ten', models.CharField(max_length=16)),
                ('ssn', models.CharField(max_length=11)),
                ('regon', models.CharField(max_length=255)),
                ('rbe', models.CharField(max_length=255)),
                ('icn', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('notes', models.TextField()),
                ('serviceaddr', models.TextField()),
                ('creationdate', models.IntegerField()),
                ('moddate', models.IntegerField()),
                ('creatorid', models.IntegerField()),
                ('modid', models.IntegerField()),
                ('deleted', models.BooleanField()),
                ('message', models.TextField()),
                ('pin', models.IntegerField()),
                ('cutoffstop', models.IntegerField()),
                ('consentdate', models.IntegerField()),
                ('divisionid', models.IntegerField()),
                ('paytime', models.IntegerField()),
                ('paytype', models.SmallIntegerField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('depositdate', models.IntegerField()),
                ('sendinvoice', models.BooleanField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
