# Generated by Django 3.0.8 on 2020-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('type', models.SmallIntegerField()),
                ('userid', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('taxid', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('comment', models.TextField()),
                ('docid', models.IntegerField()),
                ('itemid', models.SmallIntegerField()),
                ('importid', models.IntegerField(blank=True, null=True)),
                ('sourceid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('rights', models.CharField(max_length=64)),
                ('hosts', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('lastlogindate', models.IntegerField()),
                ('lastloginip', models.CharField(max_length=16)),
                ('failedlogindate', models.IntegerField()),
                ('failedloginip', models.CharField(max_length=16)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
