# Generated by Django 3.2.12 on 2022-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varname', models.CharField(max_length=250)),
                ('varsection', models.CharField(default=None, max_length=100, null=True)),
                ('varvalue', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'sysvars',
                'managed': False,
            },
        ),
    ]
