# Generated by Django 3.0.9 on 2020-08-03 23:21

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    migrations.CreateModel(
        name='RoutersType',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('type', models.CharField(max_length=255)),
        ],
        options={
            'db_table': 'routerstype',
        },
    )

    RoutersType = apps.get_model("api_rbbackup", "RoutersType")
    RoutersType.objects.bulk_create([
        RoutersType(type="Mikrotik"),
        RoutersType(type="Ubnt")
    ])


def rev(apps, schema_editor):
    # the reverse goes here if you want to copy company names into customer again if you migrate backwards.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api_rbbackup', '0003_routers_isactivated'),
    ]

    operations = [
        migrations.RunPython(forwards_func, rev),
    ]
